### ISSUE TITLE
Folder missing

### ISSUE THREAD

**Issue by qinxiaoy** [sunningzh/sunningzh.github.io#1]
Hi Shengxing,

It's expected but is there any reason for removing the folder? 

Xiaoyu

**Comment by sunningzh** [comment]
Hi Xiaoyu,

Do you mean the letter repository? I did have some trouble when backing up the repository several weeks ago. Then I recovered it from the local backup. I thought everything was OK but today I find that you are not available to this private repository again. I send a new inviting email to your GitHub email (maybe you should check your ustc email?). You can click the inviting link in the email to get access to this private repository. If you did not get the email, you can leave a message here and I will send a new one as soon as possible. 

Anyway, very sorry for the mistake. 

Shengxing

**Comment by qinxiaoy** [comment]
No problem & thank you Shengxing, it worked. I will close the issue now.

Best,
Xiaoyu
